name: module_flutter
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: 2.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter_modular: ^3.2.2+1
  flutter_svg: ^1.0.0
  flutter_translate: ^3.0.1
  dartz: ^0.10.0
  dio: ^4.0.4
  intl: ^0.17.0
  brasil_fields: ^1.4.2
  equatable: ^2.0.3
  flutter_animation_progress_bar: ^2.0.1
  snack: ^2.0.0
  modal_bottom_sheet: ^2.0.1
  shared_preferences: ^2.0.13
  pin_code_fields: ^7.3.0
  cupertino_icons: ^1.0.2
  adaptive_dialog: ^1.6.3
  responsive_sizer: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  flutter_widget_from_html: ^0.8.5

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-BoldCondensed.ttf
        - asset: fonts/Roboto-BoldCondensedItalic.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Condensed.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf

  module:
    androidX: true
    androidPackage: com.ivaas.module_flutter.module_flutter
    iosBundleIdentifier: com.ivaas.moduleflutter.moduleFlutter
